### ISSUE TITLE
Entropy of the Client Cookie

### ISSUE THREAD

**Issue by salzmdan** [NLnetLabs/draft-sury-toorop-dns-cookies-algorithms#19]
In section "Constructing a Client Cookie" it is stated that "The Client Cookie SHOULD have at least 64-bits of entropy". But the Client Cookie size is 8 bytes (RFC 7873, Section 4), so 64 bits of entropy is a theoretical maximum! Probably it should be a restriction on the Client Cookie Secret?

**Comment by vcunat** [comment]
The formulation sounds weird to me as well, and it persists in the current draft.  Ping @wtoorop

**Comment by wtoorop** [comment]
@salzmdan @vcunat Pong, sorry for not responding earlier...
The intention was to say "no less than 64 bits of entropy".
I'll change it to state just that.  OK?
