### ISSUE TITLE
Format of timestamp

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-sury-toorop-dns-cookies-algorithms#4]
Number of seconds since the Epoch, 1970-01-01 00:00:00 +0000 (UTC) in network byte order
In bind's current cookie implementation, the timestamp appears not to be in network byte order!

**Comment by salzmdan** [comment]
:+1:  + ignoring leap seconds (inspired with RRSIG's Signature Expiration)

**Comment by partim** [comment]
You also might want to state how you deal with rolling over, since the time stamp is only 32 bits.

**Comment by wtoorop** [comment]
Yes yes serial arithmetics just like with RRSIG's Signature Expiration

**Comment by salzmdan** [comment]
I would expect the value is **unsigned** 32-bit. So it shouldn't be a serious issue :-)

**Comment by wtoorop** [comment]
Resolved per commit 2e586d3
